apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: nexoryx-mlops
type: Opaque
stringData:
  POSTGRES_DB: mlops
  POSTGRES_USER: mlopsuser
  POSTGRES_PASSWORD: CHANGE_ME
  AIRFLOW_FERNET_KEY: CHANGE_ME
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: CHANGE_ME
